Added synchronized access to listeners and subscriptions
pubnub/swift pull request #189
Opened 2024-09-12 11:38 UTC by jguz-pubnub

fix(listeners): added synchronized access to listeners and subscriptions

2024-09-12 13:43 UTC, parfeon requested changes

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Helpers/WeakBox.swift
> +    return elements.lockedRead { $0 }.compactMap { $0.underlying }
`compactMap` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
    return elements.lockedRead { $0.compactMap { $0.underlying } }
```

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Helpers/WeakBox.swift
> +    elements.lockedRead { $0 }.count
`count` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
    elements.lockedRead { $0.count }
```

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Helpers/WeakBox.swift
> +  var endIndex: Set<WeakBox<Element>>.Index { return elements.lockedRead { $0 }.endIndex }
`startIndex ` and `endIndex` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
  var startIndex: Set<WeakBox<Element>>.Index { return elements.lockedRead { $0.startIndex } }
  var endIndex: Set<WeakBox<Element>>.Index { return elements.lockedRead { $0.endIndex } }
```

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Helpers/WeakBox.swift
> +    elements.lockedRead { $0[position] }.underlying
`underlying` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
    elements.lockedRead { $0[position].underlying }
```

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Helpers/WeakBox.swift
> +    elements.lockedRead { $0 }.index(after: index)
`index (after:)` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
    elements.lockedRead { $0.index(after: index) }
```

2024-09-12 13:43 UTC, parfeon commented on Sources/PubNub/Subscription/SubscriptionSession.swift
> +      },
`compactMap ` after closure, close will operate on the reference to the original `elements` (they did not mutate in `lockedRead` closure and COW not applied) but outside of lock. The following change should be more thread-safe:
```suggestion
      from: globalChannelSubscriptions.lockedRead { $0.compactMap {
        channelNamesToUnsubscribe.contains($0.key) ? $0.value : nil
      } },
      and: globalGroupSubscriptions.lockedRead { $0.compactMap {
        groupNamesToUnsubscribe.contains($0.key) ? $0.value : nil
      } },
```

2024-09-13 09:41 UTC, jguz-pubnub commented
@pubnub-release-bot release

2024-09-13 10:26 UTC, merged